# Generated by Django 4.0.3 on 2022-03-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_works_screen_work'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Автора', 'verbose_name_plural': 'Автор'},
        ),
    ]
